---
- name: Deploy monitoring
  hosts: monitoring
  become: true

  tasks:
    - name: Create monitoring directory
      ansible.builtin.file:
        path: /opt/monitoring
        state: directory
        mode: "0755"

    - name: Copy Prometheus configuration
      ansible.builtin.copy:
        src: ../files/prometheus.yaml
        dest: /opt/monitoring/prometheus.yaml
        mode: "0644"
      notify: Restart Prometheus

    - name: Copy Compose file
      ansible.builtin.copy:
        src: ../files/compose.yaml
        dest: /opt/monitoring/compose.yaml
        mode: "0644"

    - name: Start monitoring containers
      community.docker.docker_compose_v2:
        project_src: /opt/monitoring
        state: present

  handlers:
    - name: Restart Prometheus
      community.docker.docker_compose_v2:
        project_src: /opt/monitoring
        state: restarted
        services:
          - prometheus