---
- name: Deploy application and node exporter
  hosts: web
  become: true

  vars:
    aws_region: ap-southeast-1
    ecr_registry: "GANTI_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com"
    app_image: "{{ ecr_registry }}/devops-bootcamp/final-project-aishah:v1"

  tasks:
    - name: Install AWS CLI
      ansible.builtin.command: snap install aws-cli --classic
      args:
        creates: /snap/bin/aws

    - name: Get ECR login password
      ansible.builtin.command:
        cmd: "/snap/bin/aws ecr get-login-password --region {{ aws_region }}"
      register: ecr_password
      changed_when: false
      no_log: true

    - name: Login Docker to ECR
      community.docker.docker_login:
        registry_url: "{{ ecr_registry }}"
        username: AWS
        password: "{{ ecr_password.stdout }}"
      no_log: true

    - name: Run application
      community.docker.docker_container:
        name: bootcamp-app
        image: "{{ app_image }}"
        state: started
        restart_policy: unless-stopped
        pull: always
        published_ports:
          - "80:80"

    - name: Run node exporter
      community.docker.docker_container:
        name: node-exporter
        image: quay.io/prometheus/node-exporter:v1.9.1
        state: started
        restart_policy: unless-stopped
        network_mode: host
        pid_mode: host
        command:
          - "--path.rootfs=/host"
          - "--web.listen-address=10.0.0.5:9100"
        volumes:
          - "/:/host:ro,rslave"