---
- name: Install Docker on target servers
  hosts: all
  become: true

  pre_tasks:
    - name: Install Python dependencies
      ansible.builtin.apt:
        name:
          - python3-requests
          - python3-boto3
        state: present
        update_cache: true
        cache_valid_time: 3600

  roles:
    - geerlingguy.docker